# Generated by Django 5.1.3 on 2024-12-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftify', '0002_purchaseorder_purchaseorderitem_returnorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
