# Generated by Django 5.1.3 on 2024-12-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftify', '0003_userextended_profile_picture_userextended_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='address',
            field=models.OneToOneField(blank=True, help_text="User's address", null=True, on_delete=django.db.models.deletion.CASCADE, to='craftify.address'),
        ),
    ]
