# Generated by Django 5.1.3 on 2024-12-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('craftify', '0004_alter_userextended_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextended',
            options={},
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='country_code',
            field=models.CharField(blank=True, help_text='Country Code', max_length=4),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='drivers_license_number',
            field=models.CharField(blank=True, help_text="Driver's License Number", max_length=20),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile Picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='website',
            field=models.URLField(blank=True, help_text='Website'),
        ),
    ]
