# Generated by Django 5.1.3 on 2024-12-03 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftify', '0005_alter_userextended_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='website',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='craftify.address'),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='country_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='drivers_license_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
