# Generated by Django 5.1.3 on 2024-12-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftify', '0008_remove_purchaseorder_items_item_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
