# Generated by Django 5.1.3 on 2024-12-05 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftify', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='craftify_it_owner_i_06963d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('seller', 'name')},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_for_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userextended',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['seller'], name='craftify_it_seller__316553_idx'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
